services:
  - type: web
    name: dhl-backend
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://dhl-backend.onrender.com
      - key: APP_NAME
        value: "DHL Backend"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
databases:
  - name: dhl-db
    databaseName: dhl
    user: dhl_user
    plan: free
